### PR TITLE
[WIP][FEATURE] News partial

### PR DESCRIPTION
**Pull request by t3easy**
Provide a partial to render videos of ext:news the same way as content elements.

Work in progress, because TypoScript registration like 
`plugin.tx_news.view.partialRootPaths.1526542481 = EXT:video_shariff/Resources/Private/Extensions/fluid_styled_content/Partials/
`
is missing.
The rest of it works.

Maybe we can talk about how to add this. Just documentation, separate TypoScript folder...

Resolves: #24

### CODE REVIEW

**Comment by stephangrass** [comment]
Hey, that's a good feature! And this solution works very well.

**Comment by t3easy** [comment]
@froemken @pascal20997 Can we talk/write about the missing TypoScrip and how you would like to handle this?

**Comment by pascal20997** [comment]
Hey Jan, sorry for the late response. The idea is great and I'm happy for that request. What do you think about adding that TypoScript to the main static template of ext:video_shariff. If the user has no news installed, it does not throw an error or so and if the user doesn't want video_shariff for news then he can just disable it by removing the line using TypoScript.

**Comment by t3easy** [comment]
He Pascal,
perfect! I'll add the TypoScript to the PR branch.

**Comment by pascal20997** [comment]
Thank you very much :)

**Pull request merged**
